version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: unleash_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unleash
    ports:
      - "5432:5432"

  unleash:
    image: unleashorg/unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://unleash_user:password@postgres:5432/unleash
      DATABASE_SSL: "false"
      ADMIN_API_TOKENS: default:development-token
      ENABLE_ADMIN_TOKEN_FOR_FRONTEND: "true"  # ✅ add this line
    depends_on:
      - postgres
