name: Deploy to Amazon ECS via CodeDeploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: strapi-app-rutik
  ECR_REGISTRY: 607700977843.dkr.ecr.us-east-2.amazonaws.com
  ECS_CLUSTER: task11-strapi-cluster-rutik
  ECS_SERVICE: strapi-service-rutik
  TASK_DEF_FILE: ecs-task-def.json
  CONTAINER_NAME: rutik-strapi
  CODEDEPLOY_APP: StrapiCodeDeployApp-rutik
  CODEDEPLOY_GROUP: StrapiDeployGroup-dg

jobs:
  deploy:
    name: Deploy to ECS with CodeDeploy
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 🔑 Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: 🐳 Build and Push Docker Image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "Building Docker image: $ECR_REPOSITORY:$IMAGE_TAG"
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: 📄 Render new ECS Task Definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.TASK_DEF_FILE }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: 🧪 Print rendered task definition file path
        run: echo "Rendered task definition: ${{ steps.render-task.outputs.task-definition }}"

      - name: 📜 View task definition contents
        run: cat ${{ steps.render-task.outputs.task-definition }}

      - name: 🚀 Deploy via AWS CodeDeploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          codedeploy-application: ${{ env.CODEDEPLOY_APP }}
          codedeploy-deployment-group: ${{ env.CODEDEPLOY_GROUP }}
          codedeploy-appspec: appspec.yaml
