name: Dockerize and Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REGISTRY: 607700977843.dkr.ecr.us-east-2.amazonaws.com
  ECR_REPOSITORY: strapi-app-rutik
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Docker image path and extract commit SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "docker_image=${ECR_REGISTRY}/${ECR_REPOSITORY}" >> $GITHUB_ENV

      - name: Debug: List repo contents
        run: ls -R

      - name: Build Docker image
        run: |
          docker build -t $docker_image:$IMAGE_TAG .
          docker tag $docker_image:$IMAGE_TAG $docker_image:$SHORT_SHA

      - name: Push Docker image
        run: |
          docker push $docker_image:$IMAGE_TAG
          docker push $docker_image:$SHORT_SHA

      - name: Output ECR image URLs
        run: |
          echo "Image pushed with 'latest' tag: $docker_image:$IMAGE_TAG"
          echo "Image pushed with SHA tag: $docker_image:$SHORT_SHA"
